---
title: "Community"
---

The ADMB Foundation consists of ordinary and supporting members. Ordinary members have a vote in Foundation affairs and participate actively in the work of the organization.

Supporting members do not vote but promote the ADMB project primarily by paying membership fees. Please contact the Foundation for information about supporting membership.

Several organizations offered critical support during the creation of the Foundation and the start-up of the ADMB Project. These organizations are listed on our partners and benefactors.

## Foundation Members
The ADMB Foundation consists of ordinary and supporting members. Ordinary members have a vote in Foundation affairs and participate actively in the work of the organization. The following individuals are ordinary members of the foundation.

* Ian Taylor (President)
* Erik Franklin (Treasurer)
* Vanessa Trijoulet (Secretary)
* Christoffer Albertsen
* Teresa A’mar
* Johnoel Ancheta
* Casper Berg
* Mollie Brooks
* Gavin Fay
* Chris Grandin
* Andrea Havron
* Allan Hicks
* Jim Ianelli
* Kasper Kristensen
* Arni Magnusson
* Steve Martell
* Mark Maunder
* Colin Millar
* Cole Monnahan
* Anders Nielsen
* Helen Ogden
* John Sibert
* Hans Skaug
* Christine Stawitz
* Ian Taylor
* James Thorson
* Juan Valero
* Athol Whitten

## Benefactors
The following organizations provided logistical support and funding in 2007 and 2008 to help start the ADMB Foundation:

* Pelagic Fisheries Research Program
* University of Hawaii, Honolulu
* Inter-American Tropical Tuna Commission, La Jolla, California
* Marine Resource Assessment and Management Group (MARAM)
* Department of Mathematics and Applied Mathematics, University of Cape Town
* International Pacific Halibut Commission, Seattle, Washington
* AZTI-Technalia
* Second International Symposium on Tagging and Tracking Marine Fish with Electronic Devices, 8-11 October 2007, Donostia-San Sebastian, Spain
* Technical University of Denmark Department of Informatics and Mathematical Modelling

## Partnerships
A generous grant from the Gordon and Betty Moore Foundation to the National Center for Ecological Analysis and Synthesis established important new partnerships with the ADMB Foundation to further the goals of the ADMB Project.